a=int(input("Enter a number: "))
b=int(input("Enter a number: "))
print("The sum of", a, "and", b, "is", a + b)
print("The difference of", a, "and", b, "is", a - b)
print("The product of", a, "and", b, "is", a * b)
print("The quotient of", a, "and", b, "is", a / b)
print("The modulus of", a, "and", b, "is", a % b)
print("The exponent of", a, "and", b, "is", a ** b)
print("The floor division of", a, "and", b, "is", a // b)
print("The absolute value of", a, "is", abs(a))